[package]
name = "ecdsa_public_key_note"
authors = ["aztec-labs"]
compiler_version = ">=0.25.0"
type = "lib"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.54.0", directory="noir-projects/aztec-nr/aztec" }
