[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.54.0", directory="noir-projects/aztec-nr/aztec" }
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.54.0", directory="noir-projects/aztec-nr/authwit"}
ecdsa_public_key_note = { path = "../ecdsa_public_key_note" } 
